# Generated by Django 3.2.4 on 2021-07-05 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_todo_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='todo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='base.todo'),
        ),
    ]
